version: "3.6"
services:
  api:
    build: .
    image: express-base-api
    volumes:
      - "C:/volumes/express-base-api/logs:/usr/src/app/logs"
    env_file:
      - docker.env
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - redis
      - mongo
      - rabbitmq
  redis:
    image: redis
    volumes:
      - "C:/volumes/redis_docker/data:/data"
    ports:
      - 6379:6379
    command: redis-server
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - "C:/volumes/mongodb_docker/data:/data"
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - "C:/volumes/rabbitmq:/var/lib/rabbitmq/mnesia"
    ports:
      - 15672:15672
      - 5672:5672
